In [99]:
import numpy as np 
import pandas as pd

In [100]:
df = pd.read_csv(r'Iris.csv')

In [101]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [102]:
# to check how many columns are there
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [103]:
df.isnull()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [104]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [105]:
# seprate the features
X = df.drop(['Species'],axis=1)

In [106]:
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [107]:
Y = df['Species']

In [108]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [109]:
from sklearn.preprocessing import LabelEncoder

In [110]:
Y.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [111]:
lbl = LabelEncoder()
df['Species'] = lbl.fit_transform(Y)

In [112]:
Y = df['Species']

In [113]:
Y.unique()

array([0, 1, 2])

In [114]:
# input = X, Output = Y
X.shape,Y.shape

((150, 5), (150,))

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=20)

In [117]:
x_train.shape, y_train.shape

((120, 5), (120,))

In [118]:
x_test.shape, y_test.shape

((30, 5), (30,))

In [119]:
from sklearn.linear_model import LogisticRegression

In [120]:
model = LogisticRegression(solver='lbfgs',max_iter=1000)
model = model.fit(x_train,y_train)

In [121]:
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error

In [122]:
accuracy = model.score(x_train, y_train)

In [123]:
print('Accuracy', accuracy)

Accuracy 1.0


In [124]:
predict = model.predict(x_test)

In [125]:
model.score(x_test,y_test)

1.0

In [126]:
print(confusion_matrix(y_test,predict))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]
